import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import 'react-circular-progressbar/dist/styles.css';
import ReduxStoreProvider from "@/redux/ReduxStoreProvider";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxStoreProvider>
          {children}
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
